name:                lexer-plus-parser
version:             0.1.0.0
github:              "githubuser/lexer-plus-parser"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

dependencies:
- base >= 4.7 && < 5
- pretty-simple
- unordered-containers
- containers
- vector
- hashable

library:
  source-dirs: src

executables:
  lexer-plus-parser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lexer-plus-parser
